# from https://github.com/frekans7/docker-compose-lemp

version: '2'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        container_name: LEMP_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=nimda
        networks:
            - LEMP
        command: 'mysqld --innodb-flush-method=fsync'

    php:
        build:
          context: ./
          dockerfile: php.docker
        container_name: LEMP_php
        volumes:
            - ./code:/code
        ports:
            - "9000:9000"
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpMyAdmin
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - LEMP
